### PR TITLE
Updating gamedata for Filter_IsUserBanned

### PR DESCRIPTION
**Pull request by data-bomb**
Found likely engine signature for Filter_IsUserBanned based on string xrefs

### CODE REVIEW

**Comment by trollollol123** [comment]
This still crashes my server I think.

**Comment by data-bomb** [comment]
@BrutalCSEjziponken with these updates there are many causes for a sever to crash until all gamedata is stable again. could you share anything specific on BanId that you're seeing?

**Comment by trollollol123** [comment]
> @BrutalCSEjziponken with these updates there are many causes for a sever to crash until all gamedata is stable again. could you share anything specific on BanId that you're seeing?

Hm, maybe it wasnt this crashing it.. I added accelerator now. I have to wait and see if it crashes again. It was weird because it was all working, and then I added this and it crashed. I assumed it was this. :P

**Comment by data-bomb** [comment]
https://github.com/komashchenko/BanId_Fix/commit/a469d12361a6734926414b858f04820c923123fd has a different mask but could be fine (assuming it has been tested). this PR can be closed since a similar change is on master from @komashchenko

**Pull request closed without merging**
